import { type NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { getDiagnostics, diagnosticsMarkdown } from '@/lib/bug-export'

interface GitHubExportBody {
  owner: string
  repo: string
  token: string
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ bugId: string }> }
) {
  const session = await auth()
  if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { bugId } = await params
  const { owner, repo, token } = (await req.json()) as GitHubExportBody

  const bug = await db.bug.findUnique({
    where: { id: bugId },
    include: {
      report: true,
      project: {
        include: {
          organisation: { include: { members: { where: { userId: session.user.id } } } },
        },
      },
    },
  })

  if (!bug || bug.project.organisation.members.length === 0) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  const report = bug.report
  const steps = report ? (report.stepsToReproduce as string[]) : []
  const severity = report?.severity ?? 'P3'
  const diagnostics = diagnosticsMarkdown(getDiagnostics(bug.consoleLogs, bug.networkFails))

  const body = [
    report?.summary ?? `Bug captured at ${bug.pageUrl}`,
    '',
    '## Environment',
    `- **URL:** ${bug.pageUrl}`,
    `- **Browser:** ${bug.userAgent}`,
    `- **Screen:** ${bug.screenWidth}×${bug.screenHeight}`,
    `- **Captured:** ${bug.capturedAt.toISOString()}`,
    '',
    diagnostics,
    steps.length > 0
      ? ['## Steps to Reproduce', ...steps.map((s, i) => `${i + 1}. ${s}`), ''].join('\n')
      : '',
    report
      ? [
          '## Expected Behaviour',
          report.expectedBehaviour,
          '',
          '## Actual Behaviour',
          report.actualBehaviour,
          '',
          report.suspectedCause ? `## Suspected Cause\n${report.suspectedCause}\n` : '',
        ].join('\n')
      : '',
    bug.playwrightScript
      ? `## Playwright Reproduction Script\n\`\`\`typescript\n${bug.playwrightScript}\n\`\`\``
      : '',
    '',
    `---\n*Generated by [Reprod](https://reprod.dev) — Bug ID: ${bug.id}*`,
  ]
    .filter(Boolean)
    .join('\n')

  const severityLabel = severity === 'P1' ? 'bug' : severity === 'P2' ? 'bug' : 'enhancement'

  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title: report?.title ?? `Bug: ${bug.pageUrl}`,
      body,
      labels: [severityLabel, severity.toLowerCase()],
    }),
  })

  if (!res.ok) {
    const err = (await res.json()) as { message?: string }
    return NextResponse.json(
      { error: err.message ?? 'GitHub API error' },
      { status: res.status }
    )
  }

  const issue = (await res.json()) as { html_url: string; number: number }
  return NextResponse.json({ issueUrl: issue.html_url, issueNumber: issue.number })
}
